use tonic::{transport::Server, Request, Response, Status, Streaming};
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;
use tracing::{info, warn};

// Include the autogenerated gRPC stubs
pub mod trace_stream {
    tonic::include_proto!("trace_stream");
}
use trace_stream::prover_stream_server::{ProverStream, ProverStreamServer};
use trace_stream::{TraceChunk, ProverStatus};

#[derive(Default)]
pub struct ZkVmProverService {}

#[tonic::async_trait]
impl ProverStream for ZkVmProverService {
    type StreamExecutionTraceStream = ReceiverStream<Result<ProverStatus, Status>>;

    async fn stream_execution_trace(
        &self,
        request: Request<Streaming<TraceChunk>>,
    ) -> Result<Response<Self::StreamExecutionTraceStream>, Status> {
        let mut stream = request.into_inner();

        // Create a channel to stream status back to the client
        let (tx, rx) = mpsc::channel(128);

        tokio::spawn(async move {
            let mut session_id = String::new();
            let mut total_chunks = 0;
            let mut trace_buffer = Vec::new();

            while let Some(chunk_result) = stream.message().await.unwrap_or(None) {
                let chunk = chunk_result;
                session_id = chunk.session_id.clone();
                total_chunks += 1;
                
                // Append serialized trace steps to RAM buffer
                trace_buffer.extend_from_slice(&chunk.payload);

                info!("Received chunk {} for session {}", chunk.chunk_index, session_id);

                let status = ProverStatus {
                    session_id: session_id.clone(),
                    job_id: format!("job-{}", session_id),
                    message: format!("Processed chunk {}", chunk.chunk_index),
                    is_completed: false,
                    proof_data: vec![],
                };

                if let Err(e) = tx.send(Ok(status)).await {
                    warn!("Client disconnected prematurely: {}", e);
                    return;
                }

                if chunk.is_final {
                    info!("Received final chunk. Total size: {} bytes. Commencing STARK proving...", trace_buffer.len());
                    
                    // Here we would deserialize `trace_buffer` into an ExecutionTrace 
                    // and feed it to the STARK prover (e.g. halo2 implementation).
                    
                    // Simulate proof generation time
                    tokio::time::sleep(tokio::time::Duration::from_millis(1500)).await;
                    
                    let final_status = ProverStatus {
                        session_id: session_id.clone(),
                        job_id: format!("job-{}", session_id),
                        message: "Proof generated successfully".to_string(),
                        is_completed: true,
                        proof_data: vec![0xDE, 0xAD, 0xBE, 0xEF], // Mock STARK proof bytes
                    };
                    
                    let _ = tx.send(Ok(final_status)).await;
                    break;
                }
            }
        });

        Ok(Response::new(ReceiverStream::new(rx)))
    }
}

pub async fn start_grpc_server(addr: std::net::SocketAddr) -> Result<(), Box<dyn std::error::Error>> {
    let service = ZkVmProverService::default();
    info!("Starting high-performance gRPC Prover Stream on {}", addr);

    Server::builder()
        .add_service(ProverStreamServer::new(service))
        .serve(addr)
        .await?;

    Ok(())
}
